# Generated by Django 5.1 on 2024-08-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_chat_id', models.CharField(max_length=50, verbose_name='Admin Chat ID')),
            ],
        ),
    ]
